# Tutorial Basico Numpy

O NumPy (Python Numérico) é uma biblioteca Python de código aberto usada em quase todos os campos da ciência e engenharia. É o padrão universal para trabalhar com dados numéricos em Python e está no centro dos ecossistemas científicos Python e PyData.

Conteudo :
- Introdução
- Criação de arrays 
- Indexação dos elementos
- Manipulação de formatos
- Operações basicas
- Salvando vetores


Material auxiliar:
https://numpy.org/devdocs/user/quickstart.html

#### Import Numpy


In [1]:
import numpy as np

## Introdução

Por que Utilizar o numpy?

- Simplifica o calculo em uma serie de situações.

- Utiliza menos espaço na memoria devido a uma estrutura de dados otimizada.

- Tem uma performance maior que uma implementação em python simples

In [2]:
import time
import sys

### Conveniência

Vamos demostrar a conveniência de se utilizar numpy em exemplo bem simples.

In [3]:
altura = [1.73, 1.68, 1.71, 1.89, 1.79]

peso = [65.4, 59.2, 63.6, 88.4, 68.7]

Suponha que quero calcular imc de forma rapida

In [4]:
imc = peso / altura ** 2

TypeError: ignored

In [5]:
imc = []
for i in range(len(altura)):
    imc.append( peso[i] / altura[i] ** 2 )
imc

[21.85171572722109,
 20.97505668934241,
 21.750282138093777,
 24.74734749867025,
 21.44127836209856]

Utilizando numpy

In [6]:
np_altura = np.array(altura)
np_peso = np.array(peso)

imc = np_peso / np_altura ** 2

imc

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

### Gestão de memoria

In [7]:
# Em python 

array_py = range(1000)
print(sys.getsizeof(array_py[0])*len(array_py))
# Com numpy 
array_numpy = np.arange(1000)
print(array_numpy.size*array_numpy.itemsize)

24000
8000


### Performance

In [60]:
SIZE = 100000000

l1 = range(SIZE)
l2 = range(SIZE)

a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

In [61]:
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print(f'Utilizando listas em pytho levou: {(time.time()-start)} segundos')

start = time.time()
result = a1 + a2
print(f'Utilizando numpy levou: {(time.time()-start)} segundos')


Utilizando listas em pytho levou: 13.343095302581787 segundos
Utilizando numpy levou: 2.2576181888580322 segundos


## Criação de arrays

**numpy.arange([start,] stop[, step,], dtype=None)**



In [16]:
arr = np.arange(15)
print(f'Formato: {arr.shape} Tamanho dos itens em bytes: {arr.itemsize}  typo de dado: {arr.dtype}')
arr

Formato: (15,) Tamanho dos itens em bytes: 8  typo de dado: int64


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr2 = np.arange(15,dtype=np.float128)
print(f'Formato: {arr2.shape} Tamanho dos itens em bytes: {arr2.itemsize}  typo de dado: {arr2.dtype}')
arr2

Formato: (15,) Tamanho dos itens em bytes: 16  typo de dado: float128


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.], dtype=float128)

In [ ]:
a = np.array([2,3,4])
print(a.shape)
a

(3,)


array([2, 3, 4])

In [17]:
b = np.zeros((3, 4))
print(b.shape)
b

(3, 4)


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
c = np.ones( (2,3,4), dtype=np.int16 )
print(c.shape)
c

(2, 3, 4)


array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

## Indexação dos elementos

A indexação e acesso aos elementos é semelhante as listas em python

In [ ]:
arr[5]

5

In [ ]:
arr[3:7]

array([3, 4, 5, 6])

In [ ]:
arr[-1]

14

## Manipulação de formatos

In [ ]:
t = np.random.random(20)
t

array([0.0767404 , 0.53999172, 0.41985858, 0.82777886, 0.77526389,
       0.36203078, 0.08962058, 0.03705304, 0.0376812 , 0.68982442,
       0.55617403, 0.82970163, 0.35892443, 0.71157651, 0.16182851,
       0.24817654, 0.85049478, 0.30143967, 0.42066023, 0.90546069])

**np.reshape(a, newshape, order='C')**

In [ ]:
t.reshape((5,4))

array([[0.0767404 , 0.53999172, 0.41985858, 0.82777886],
       [0.77526389, 0.36203078, 0.08962058, 0.03705304],
       [0.0376812 , 0.68982442, 0.55617403, 0.82970163],
       [0.35892443, 0.71157651, 0.16182851, 0.24817654],
       [0.85049478, 0.30143967, 0.42066023, 0.90546069]])

In [ ]:
t.reshape((10,2))

array([[0.41045098, 0.87257813],
       [0.98574493, 0.3015985 ],
       [0.11234521, 0.34271121],
       [0.45667824, 0.59749741],
       [0.48919407, 0.02279703],
       [0.59663665, 0.10481371],
       [0.72429685, 0.53140185],
       [0.33344443, 0.38579518],
       [0.02427754, 0.62548913],
       [0.18942518, 0.75481667]])

In [19]:
c = np.ones( (2,3,4), dtype=np.int16 )
print(c.shape)
c.T  # Transposição
print(c.T.shape)

(2, 3, 4)
(4, 3, 2)


In [ ]:
a = np.arange(30)

b = a.reshape((2, -1, 3))  # -1 significa calcule o que for necessário

b.shape

(2, 5, 3)

In [ ]:
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

## Operações basicas

In [ ]:
a = np.array( [20,30,40,50] )

b = np.arange( 4 )

In [ ]:
a - b

array([20, 29, 38, 47])

In [ ]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [ ]:
A = np.array([[1,1], 
              [0,1]])

B = np.array([[2,0],
              [3,4]] )

In [ ]:
A * B # mutiplicação Ponto a ponto

array([[2, 0],
       [0, 4]])

In [ ]:
A @ B # mutiplicação matricial 

array([[5, 4],
       [3, 4]])

In [ ]:
A.dot(B)

array([[5, 4],
       [3, 4]])

### Agregação

In [21]:
C = np.array([[1,2],
              [3,4],
              [5,6]])
print(C.min())
print(C.max())
print(C.sum())
print(C.mean())
print(C.std())

1
6
21
3.5
1.707825127659933


np.sum(a, axis=None, dtype=None, out=None, keepdims=numpy._globals._NoValueType instance, initial=numpy._globals._NoValueType instance, where=numpy._globals._NoValueType instance)

In [ ]:
C.sum(axis=0)

array([ 9, 12])

In [ ]:
C.sum(axis=1)

array([ 3,  7, 11])

### Filtragem

In [26]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

## Salvando vetores

Salvando as variaveis:
Depois de fazer tudo o que você precisa fazer com suas matrizes, você também pode salvá-las em um arquivo. Se você deseja salvar a matriz em um arquivo de texto, pode usar o savetxt ()

Uma outra forma de salvar bastante utilizada é o metodo save(). Ele permite salvar em um arquivo binario com o formato .npy

In [29]:
np.save??

In [27]:
np.savetxt('teste.txt', a, delimiter=',')
np.save("array.npy",a)

Parar ler variaveis salvas no formato npy utilizamos o método load().

In [30]:
test=np.load("array.npy")
print(test)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## Problemas pra fixar 

5. Como substituir itens que satisfazem uma condição por outro valor na matriz numpy?

Substituia todos os numeros pares do vetor *arr* por -1

```
Entrada :

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Saída esperada:

>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

```

14. Como extrair todos os números entre um determinado intervalo de um vetor numpy?

Obtenha todos os itens entre 5 e 10 de *a*.
```
Entrada:

a = np.array([2, 6, 1, 9, 10, 3, 27])

Saída esperada:

array([ 6,  9, 10])
```
20. Como criar uma matriz 2D contendo valores aleatórios entre 5 e 10?

```
Entrada:

np.random.seed(100)

arr = ____

Saída esperada:

array([[5.20920212, 5.18532822, 8.10837689],
       [5.21969749, 7.97862378, 9.81168315],
       [7.17194101, 7.81622475, 7.27407375],
       [7.43170418, 6.94002982, 5.81764938],
       [5.33611195, 9.17541045, 8.37283205]])
```



# Proximos Passos

Tutorial no datacamp é bastante completo e uma boa forma de aprofundar o que foi apresentado nesta introdução.

 - https://www.datacamp.com/community/tutorials/python-numpy-tutorial

Cheat Sheet sintetizando o kit basico do numpy 

 - https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf

 Lista de exercícios NumPy

 - https://www.machinelearningplus.com/python/101-numpy-exercises-python/

Sugestão itens:
[5, 8, 11, 14, 18, 20, 33, 34, 39, 45, 56, 58, 62]
 