# Tutorial Basico Numpy

O NumPy (Python Numérico) é uma biblioteca Python de código aberto usada em quase todos os campos da ciência e engenharia. É o padrão universal para trabalhar com dados numéricos em Python e está no centro dos ecossistemas científicos Python e PyData.

Conteudo :
- Introdução
- Criação de arrays 
- Indexação dos elementos
- Manipulação de formatos
- Operações basicas


Material auxiliar:
https://numpy.org/devdocs/user/quickstart.html
https://www.datacamp.com/community/tutorials/python-numpy-tutorial

#### Import Numpy


In [0]:
import numpy as np

## Introdução

In [0]:
altura = [1.73, 1.68, 1.71, 1.89, 1.79]

peso = [65.4, 59.2, 63.6, 88.4, 68.7]

Suponha que quero calcular imc de forma rapida

In [0]:
imc = peso / altura ** 2

TypeError: ignored

In [0]:
imc = []
for i in range(len(altura)):
    imc.append( peso[i] / altura[i] ** 2 )
imc

[21.85171572722109,
 20.97505668934241,
 21.750282138093777,
 24.74734749867025,
 21.44127836209856]

Utilizando numpy

In [0]:
np_altura = np.array(altura)
np_peso = np.array(peso)

imc = np_peso / np_altura ** 2

imc

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

## Criação de arrays

In [0]:
arr = np.arange(15)
print(arr.shape)
arr

(15,)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [0]:
a = np.array([2,3,4])
print(a.shape)
a

(3,)


array([2, 3, 4])

In [0]:
b = np.zeros((3, 4))
print(b.shape)
b

(3, 4)


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [0]:
c = np.ones( (2,3,4), dtype=np.int16 )
print(c.shape)
c

(2, 3, 4)


array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

## Indexação dos elementos

A indexação e acesso aos elementos é semelhante as listas em python

In [0]:
arr[5]

5

In [0]:
arr[3:7]

array([3, 4, 5, 6])

In [0]:
arr[-1]

14

## Manipulação de formatos

In [0]:
t = np.random.random(20)
t

array([0.41045098, 0.87257813, 0.98574493, 0.3015985 , 0.11234521,
       0.34271121, 0.45667824, 0.59749741, 0.48919407, 0.02279703,
       0.59663665, 0.10481371, 0.72429685, 0.53140185, 0.33344443,
       0.38579518, 0.02427754, 0.62548913, 0.18942518, 0.75481667])

In [0]:
t.reshape((4,5))

array([[0.41045098, 0.87257813, 0.98574493, 0.3015985 , 0.11234521],
       [0.34271121, 0.45667824, 0.59749741, 0.48919407, 0.02279703],
       [0.59663665, 0.10481371, 0.72429685, 0.53140185, 0.33344443],
       [0.38579518, 0.02427754, 0.62548913, 0.18942518, 0.75481667]])

In [0]:
t.reshape((10,2))

array([[0.41045098, 0.87257813],
       [0.98574493, 0.3015985 ],
       [0.11234521, 0.34271121],
       [0.45667824, 0.59749741],
       [0.48919407, 0.02279703],
       [0.59663665, 0.10481371],
       [0.72429685, 0.53140185],
       [0.33344443, 0.38579518],
       [0.02427754, 0.62548913],
       [0.18942518, 0.75481667]])

In [0]:
c = np.ones( (2,3,4), dtype=np.int16 )
print(c.shape)
c.T  # Transposição
print(c.T.shape)

(2, 3, 4)
(4, 3, 2)


In [0]:
a = np.arange(30)

b = a.reshape((2, -1, 3))  # -1 significa calcule o que for necessário

b.shape

(2, 5, 3)

In [0]:
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

## Operações basicas

In [0]:
a = np.array( [20,30,40,50] )

b = np.arange( 4 )

In [0]:
a - b

array([20, 29, 38, 47])

In [0]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [0]:
a < 35

array([ True,  True, False, False])

In [0]:
A = np.array([[1,1], 
              [0,1]])

B = np.array([[2,0],
              [3,4]] )

In [0]:
A * B # mutiplicação Ponto a ponto

array([[2, 0],
       [0, 4]])

In [0]:
A @ B # mutiplicação matricial 

array([[5, 4],
       [3, 4]])

In [0]:
A.dot(B)

array([[5, 4],
       [3, 4]])

# Proximos Passos

Tutorial no datacamp é bastante completo e uma boa forma de aprofundar o que foi apresentado nesta introdução.

 - https://www.datacamp.com/community/tutorials/python-numpy-tutorial


Cheat Sheet sintetizando o kit basico do numpy 

 - https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf

 